# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0060dafe92d9a78be9dcdc38fe0ae72bb12e9fd1977f82fbe70d9ae5319530f3882c1a69c2310604efdf24cb101c09859b1303e6027b78390f4e7e026dece91a

test:
  secret_key_base: 45a9d60f0975ff4196b724ebd4175ea5236e7e5aa9aaa92380aab66d5a66896512a0673ee048cdba298e01f13f103a62c4030f6936e364203c7d85594d405bb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
